### ISSUE TITLE
按照步骤操作的 但是网页文本框里啥都没有

### ISSUE THREAD

**Issue by Sinderwella** [44670/buyonghenmafanhenleijiunengfanyiyouxi#1]
已经提示我去网站看翻译了 但是并没有文本显示出来

**Comment by 44670** [comment]
是哪个游戏？

**Comment by QSZNO2** [comment]
你好我也遇到了相同的问题.
游戏：流行之神1
情况：
1. PPSSPP上仅显示waiting for connection
2. cmd界面上仅显示：PPSSPP: PSP user ram base addr: 10020000
Text extraction service started at port:  8052
Visit http://44670.org/fanyi for translations!
3. 用chrome打开 https://44670.github.io/buyonghenmafanhenleijiunengfanyiyouxi/fanyi.html ，并没有出现任何字符

**Comment by QSZNO2** [comment]
> 你好我也遇到了相同的问题.
> 游戏：流行之神1
> 情况：
> 
> PPSSPP上仅显示waiting for connection
> cmd界面上仅显示：PPSSPP: PSP user ram base addr: 10020000
> Text extraction service started at port:  8052
> Visit http://44670.org/fanyi for translations!
> 用chrome打开 https://44670.github.io/buyonghenmafanhenleijiunengfanyiyouxi/fanyi.html ，并没有出现任何字符

另外我已经尝试过先即时存档再读档，并尝试过重新启动cmd与ppsspp，均不能解决问题

**Comment by 44670** [comment]
PPSSPP 的版本是多少呢？

**Comment by QSZNO2** [comment]
> PPSSPP 的版本是多少呢？
v1.3呀，cmd上能显示到PPSSPP的被成功检测。我观察好像是server没有接收到request。
1. 因为do_GET在serveforever()运行后一直没有被调用过
2. 另外我单独使用lxzs1中的文本读取函数，能够从ppsspp读取到unicode编码的文本，通过转码后显示的文本也与游戏内一致。

我感觉是不是https://44670.github.io/buyonghenmafanhenleijiunengfanyiyouxi/fanyi.html ，这个网页并没有向server发出request？

**Comment by 44670** [comment]
哦哦，我刚发现那个页面确实有问题，加载jquery的尝试因为是https所以被block了。
已经修复了。

**Comment by QSZNO2** [comment]
> 哦哦，我刚发现那个页面确实有问题，加载jquery的尝试因为是https所以被block了。
> 已经修复了。

嗯嗯。我昨天也通过本地连接的方式实现了（没怎么接触过网络相关变成瞎改的哈哈哈）
1. 把fanyi.html改成index.html
2. 在chrome上输入127.0.0.1:8052，导向index.html

好像这样也可以实现（我不懂html，server这方面的编程，瞎改的哈哈哈哈）
